
export const API_URL = {
  GET: process.env.NEXT_PUBLIC_API_URL_GET,
  POST: process.env.NEXT_PUBLIC_API_URL_POST,
  PATCH: process.env.NEXT_PUBLIC_API_URL_PATCH,
  DELETE: process.env.NEXT_PUBLIC_API_URL_DELETE,
  DELETE_COMPLETED_ALL: process.env.NEXT_PUBLIC_API_URL_DELETE_COMPLETED_ALL,
  LOGIN: process.env.NEXT_PUBLIC_API_URL_LOGIN,
  REGISTER: process.env.NEXT_PUBLIC_API_URL_REGISTER
}
